### PR TITLE
Update UIColorExtension.swift

### PR DESCRIPTION
**Pull request by dhern2**
`count` function called on a String gives a compiler error, use instead `countElements`.

### CODE REVIEW

**Comment by yeahdongcn** [comment]
What is your Xcode version?

**Comment by dhern2** [comment]
Xcode 6.2 (6C131e)

**Comment by yeahdongcn** [comment]
Better upgrade to the latest Xcode 6.3 with the new swift syntax.

**Comment by dhern2** [comment]
You're right, thanks @yeahdongcn I will need to update :]

**Pull request closed without merging**
