### PR TITLE
UInt32 for the argument

### PR DESCRIPTION
**Pull request by uny**
This pull request includes:
1. Xcode Project with shared scheme (New version carthage seems to find no shared scheme for current [UIColor-Hex-Swift](https://github.com/yeahdongcn/UIColor-Hex-Swift))
2. XCTestCase instead of Sample
3. `init(hex: UInt32)` instead of `int(rgba: String)`

`3.` is just my suggestion.
I wondered if I should make a new repository, but too similar purpose to do so.
UInt32 argument leaves us from many exceptions:
* Does it include `#`?
* Is it hex format? (ex. `#FGFFFF`)
* Is it not too long? (ex. `#FFFFFFFFF`)

So, I think UInt32 argument is better than String for UIColor-Hex.
Your repository is very famous for UIColor extension for Hex format, so I would like to hear your opinion.

---

I created initializers for each format.
* `init(hex3: UInt16, alpha: CGFloat = 1)`
* `init(hex4: UInt16)`
* `init(hex6: UInt32, alpha: CGFloat = 1)`
* `init(hex8: UInt32)`

### CODE REVIEW

**Comment by hummer98** [comment]
:+1:

**Comment by yeahdongcn** [comment]
:+1:

**Comment by uny** [comment]
Sorry, this method cannot distinguish `0x0123` and `0x123`.

**Comment by uny** [comment]
Modified.

> I created initializers for each format.
* `init(hex3: UInt16, alpha: CGFloat = 1)`
* `init(hex4: UInt16)`
* `init(hex6: UInt32, alpha: CGFloat = 1)`
* `init(hex8: UInt32)`

**Comment by yeahdongcn** [comment]
I just got my Mac back, I will check this change soon.

**Pull request merged**
