### PR TITLE
golden path program

### PR DESCRIPTION
**Pull request by 100mango**
use guard to create a more clear and elegant implementation

### CODE REVIEW

**Comment by yeahdongcn** [comment]
I just got my Mac back, I will check this change soon.

**Comment by yeahdongcn** [comment]
I've done some similar changes on the master branch, could you please have a review?

**Comment by 100mango** [comment]
Yep.I think we share the same idea. But I prefer not to throw an error.A default color is safer.

**Comment by yeahdongcn** [comment]
But I met some problem trying your code, I don't know how to fix them. Could you give me some suggestions?
default

**Comment by 100mango** [comment]
hey.犯了个小错误,当时把我自己的实现放了上来。现在已经修改好了。你Review一下。

**Comment by yeahdongcn** [comment]
改了一下，看看？

**Comment by 100mango** [comment]
你直接看file changed就有~

主要改动如下：

~~~objective-c
     guard (rgba.hasPrefix("#")) else{
            print("Invalid RGB string, missing '#' as prefix")
            self.init(red:0, green:0, blue:0, alpha:1)
            return
        }
~~~

**Comment by yeahdongcn** [comment]
我在master branch中实现了类似的内容，这个就关了吧。

**Pull request closed without merging**
